### ISSUE TITLE
Выбор устройств в домашней сети, который будут ходить напрямую (без VPN)

### ISSUE THREAD

**Issue by xeeqqw** [maksimkurb/ansible-keenetic-domain-routing#1]
Привет!

Подскажи, пожалуйста, есть ли возможность задать список устройств в домашней сети (ip адреса), чей трафик будет идти напрямую (в обход VPN)?

**Comment by maksimkurb** [comment]
Добрый день. Извиняюсь, что поздно, но отвечу. 

В данном скрипте такое не поддерживается, его развитие далее не планируется.
Сейчас я разрабатываю новое решение под Keenetic, которое позволит быстро загружать и обновлять большие списки адресов в Keenetic: https://github.com/maksimkurb/keenetic-pbr

keenetic-pbr должен поддерживать маршрутизацию на разные интерфейсы по отдельным спискам путём добавления нескольких ipset-ов в конфигурацию.

У ipset'а, который будет идти напрямую, `priority` должен быть меньше (допустим, 998), чем у `ipset`, который будет вести трафик через VPN (допустим, 1001).
